getwd()
setwd("/Users/TAEHEEJUNG/Downloads")
load("daily_prices.Rdata")
load("daily_volatil.Rdata")
load("daily_volume.Rdata")
#install.packages("reshape")
library(reshape)
col <- c(colnames(daily_prices))
col <- col[-1]
md <- melt(daily_prices, id= c("date"))
mdv <- melt(daily_volatil, id = c("date"))
mdvv <-  melt(daily_volume, id = c("date")) 

md_sel <- subset(md, variable %in% c("AAPL","GOOG","AMZN","MSFT","FB"))
md_sel <- subset(md_sel, !is.na(value))
mdv_sel <- subset(mdv, variable %in% c("AAPL","GOOG","AMZN","MSFT","FB"))
mdv_sel <- subset(mdv_sel, !is.na(value))
mdvv_sel <- subset(mdvv, variable %in% c("AAPL","GOOG","AMZN","MSFT","FB"))
mdvv_sel <- subset(mdvv_sel, !is.na(value))
head(md_sel)
head(mdv_sel)
head(mdvv_sel)

daily_tot <- merge(md_sel, mdv_sel, by = c("date", "variable"), all.x = TRUE)
daily_tot <- merge(daily_tot, mdvv_sel, by = c("date", "variable"), all.x = TRUE)
colnames(daily_tot) <- c("ym", "ticker", "last_price", "volatil", "volume")
head(daily_tot)
write.csv(daily_tot, file = "daily_price_5comp.csv")
